name: imx8mm-evk
summary: NXP i.MX8M Mini EVK support package
description: |
 Support files for booting i.MX8M Mini EVK board

version: 22-1
type: gadget

base: core22

architectures:
  - build-on: [amd64, arm64]
    build-for: arm64

confinement: strict
grade: stable

build-packages:
  - bison
  - build-essential
  - device-tree-compiler
  - flex
  - libgnutls28-dev
  - libssl-dev
  - libxml2-dev
  - pkgconf
  - python3
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - wget
  - zlib1g-dev
  - on amd64:
    - gcc-${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    - libc6-dev-${CRAFT_ARCH_BUILD_FOR}-cross
    - uuid-dev:${CRAFT_ARCH_BUILD_FOR}
    - uuid-dev
  - on arm64:
    - gcc
    - uuid-dev

package-repositories:
   - type: apt
     architectures: [$CRAFT_ARCH_BUILD_FOR]
     formats: [deb, deb-src]
     components: [main]
     suites: [noble, noble-updates, noble-backports]
     key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
     url: http://ports.ubuntu.com/ubuntu-ports
