name: imx8mm-evk
summary: NXP i.MX8M Mini EVK support package
description: |
 Support files for booting i.MX8M Mini EVK board
version: 20-1
type: gadget

base: core20

architectures:
  - build-on: [amd64, arm64]
    run-on: arm64

confinement: strict
grade: stable

build-packages:
    - bison
    - build-essential
    - device-tree-compiler
    - flex
    - gcc-aarch64-linux-gnu
    - libxml2-dev
    - libssl-dev
    - python3
    - python3-crypto
    - python3-pyelftools
    - python3-pycryptodome
    - wget
    - zlib1g-dev
