#!/bin/sh

# if tee is connected, enable services
if snapctl is-connected tee-storage; then
  snapctl start --enable "${SNAP_INSTANCE_NAME}.tee-supplicant"
  snapctl start --enable "${SNAP_INSTANCE_NAME}.p11-kit-servers"
fi
