#!/bin/sh

# try to setup mount for tee-storage
# ignore error, once hooks is connected we will try again
snapctl mount \
        --persistent \
        -t ext4 \
        -o rw \
        "/dev/disk/by-partlabel/tee-storage" \
        "${SNAP_COMMON}/tee-storage" \
        || true

# Start service to generate device
# Reenable when interfaces are auto connected
# snapctl start "${SNAP_INSTANCE_NAME}.generate-hw-id-key" || true &
